config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'go' => 'urls#new'

  get 'go/:alias' => 'go#show'

  root 'go#index'

  post 'go/create'
  

  resources :urls

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/go_controller.rb
class GoController < ApplicationController
  def index
  	#@randomUrl = Url.new
  end

  def show
  	 @url = Url.find_by_alias(params[:alias])
    if @url
      redirect_to(@url[:http])
    else
      respond_to do |format|
      format.html { redirect_to new_url_url, notice: 'This Alias Was Not Found. Create A New One?' }
      format.json { render :show, status: :created, location: @url }
      end
    end 
  end

  def create
  	@randomUrl = params[:randomUrl]
  	key = (('a'..'z').to_a + ('0'..'9').to_a + ('A'..'Z').to_a).to_a.shuffle[1..7].join
  	@url = Url.new(
  		alias: key,
  		http: @randomUrl[:http]
  		)

  	respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end

  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:alias, :http, :UUID, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/go_helper.rb
module GoHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/go/index.html.erb
<h1>Random alias urlshortner</h1>

<%= form_for(:randomUrl, url: go_create_path) do |f| %>


  <!-- <div class="field">
    <%= f.label :alias %><br>
    <%= f.text_field :alias %>
  </div> -->
  <div class="field">
    <%= f.label :http %><br>
    <%= f.text_field :http %>
  </div>
  <!-- <div class="field">
    <%= f.label :UUID %><br>
    <%= f.text_field :UUID %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TempUrl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alias %><br>
    <%= f.text_field :alias %>
  </div>
  <div class="field">
    <%= f.label :http %><br>
    <%= f.text_field :http %>
  </div>
  <div class="field">
    <%= f.label :UUID %><br>
    <%= f.text_field :UUID %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<h1>Listing urls</h1>

<table>
  <thead>
    <tr>
      <th>Alias</th>
      <th>Http</th>
      <th>Uuid</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.alias %></td>
        <td><%= url.http %></td>
        <td><%= url.UUID %></td>
        <td><%= url.user_id %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<% if notice %>

<h2><%= notice %></h2>

<% else %>
	
<h1>New url</h1>

<% end %>


<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alias:</strong>
  <%= @url.alias %>
</p>

<p>
  <strong>Http:</strong>
  <%= @url.http %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @url.UUID %>
</p>

<p>
  <strong>User:</strong>
  <%= @url.user_id %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>